from time import sleep
import turtle


def stages(tries):
    window = turtle.Screen()
    window.bgcolor("red")
    if tries == 1:
        turtle.circle(50)
        turtle.righturtle(45)
        turtle.forward(150)
        turtle.backward(150)
        turtle.righturtle(90)
        turtle.forward(150)
        turtle.backward(150)
        turtle.lefturtle(45)
        turtle.forward(200)
        turtle.righturtle(45)
        turtle.forward(100)
        turtle.backward(100)
        turtle.lefturtle(90)
        turtle.forward(100)
        sleep(1)
    elif tries == 2:
        turtle.circle(50)
        turtle.righturtle(45)
        turtle.forward(150)
        turtle.backward(150)
        turtle.righturtle(90)
        turtle.forward(150)
        turtle.backward(150)
        turtle.lefturtle(45)
        turtle.forward(200)
        turtle.righturtle(45)
        turtle.forward(100)
        sleep(1)
    elif tries == 3:
        turtle.circle(50)
        turtle.righturtle(45)
        turtle.forward(150)
        turtle.backward(150)
        turtle.righturtle(90)
        turtle.forward(150)
        turtle.backward(150)
        turtle.lefturtle(45)
        turtle.forward(200)
        sleep(1)
    elif tries == 4:
        turtle.circle(50)
        turtle.righturtle(45)
        turtle.forward(150)
        turtle.backward(150)
        turtle.righturtle(45)
        turtle.forward(150)
        sleep(1)
    elif tries == 5:
        turtle.circle(50)
        turtle.righturtle(90)
        turtle.forward(150)
        sleep(1)
    elif tries == 6:
        turtle.circle(50)
        sleep(1)
